import{app,BrowserWindow,dialog,ipcMain}from'electron';import path from'node:path';import fs from'node:fs/promises';import crypto from'node:crypto';import sharp from'sharp';
const allowedExt=new Set(['.png','.webp','.jpg','.jpeg','.gif','.svg','.mp4']);let roots=new Set<string>();
const safe=(candidate:string)=>{const resolved=path.resolve(candidate);if(![...roots].some(r=>resolved===r||resolved.startsWith(r+path.sep)))throw new Error('Percorso non autorizzato');return resolved};
async function atomic(file:string,data:string){safe(file);const temp=`${file}.${crypto.randomUUID()}.tmp`;await fs.writeFile(temp,data);await fs.rename(temp,file)}
function createWindow(){const win=new BrowserWindow({width:1440,height:900,minWidth:1080,minHeight:700,backgroundColor:'#101525',webPreferences:{contextIsolation:true,nodeIntegration:false,sandbox:true,preload:path.join(__dirname,'preload.js')}});win.webContents.setWindowOpenHandler(()=>({action:'deny'}));win.webContents.on('will-navigate',e=>e.preventDefault());if(process.env.VITE_DEV_SERVER_URL)win.loadURL(process.env.VITE_DEV_SERVER_URL);else win.loadFile(path.join(__dirname,'../dist/index.html'))}
app.whenReady().then(createWindow);app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()});
ipcMain.handle('project:open',async()=>{const r=await dialog.showOpenDialog({filters:[{name:'Progetto LayerForge',extensions:['layerforge','json']}],properties:['openFile']});if(r.canceled)return null;const file=r.filePaths[0];roots.add(path.dirname(file));return{file,data:JSON.parse(await fs.readFile(file,'utf8'))}});
ipcMain.handle('project:save',async(_e,data)=>{const r=await dialog.showSaveDialog({defaultPath:'progetto.layerforge',filters:[{name:'Progetto LayerForge',extensions:['layerforge']}]});if(r.canceled||!r.filePath)return null;roots.add(path.dirname(r.filePath));await atomic(r.filePath,JSON.stringify(data,null,2));await fs.copyFile(r.filePath,`${r.filePath}.backup`);return r.filePath});
ipcMain.handle('assets:import',async()=>{const r=await dialog.showOpenDialog({properties:['openDirectory']});if(r.canceled)return null;const root=r.filePaths[0];roots.add(root);const dirs=(await fs.readdir(root,{withFileTypes:true})).filter(x=>x.isDirectory()).sort((a,b)=>a.name.localeCompare(b.name,undefined,{numeric:true}));const layers=[];for(const dir of dirs){const folder=safe(path.join(root,dir.name));const files=(await fs.readdir(folder,{withFileTypes:true})).filter(x=>x.isFile()&&allowedExt.has(path.extname(x.name).toLowerCase()));const traits=[];for(const file of files){const full=safe(path.join(folder,file.name));let warning='';if(path.extname(full)!=='.mp4')try{const m=await sharp(full,{animated:true}).metadata();warning=m.width&&m.height?`${m.width}×${m.height}`:'Formato leggibile'}catch{warning='File non leggibile'}traits.push({id:crypto.randomUUID(),name:path.parse(file.name).name,metadataName:path.parse(file.name).name,path:full,weight:1,enabled:warning!=='File non leggibile',warning})}layers.push({id:crypto.randomUUID(),name:dir.name.replace(/^\d+[ _-]*/,''),presence:1,allowNone:false,traits})}return layers});
ipcMain.handle('collection:export',async(_e,payload:any)=>{const r=await dialog.showOpenDialog({properties:['openDirectory','createDirectory']});if(r.canceled)return null;const out=path.join(r.filePaths[0],`LayerForge-${Date.now()}`);roots.add(out);for(const d of['assets','metadata','csv','reports','project'])await fs.mkdir(path.join(out,d),{recursive:true});const rows=['tokenId,nome,dna'];for(const item of payload.items){const meta=payload.metadata.find((x:any)=>x.tokenId===item.tokenId)?.data;await atomic(path.join(out,'metadata',`${item.tokenId}.json`),JSON.stringify(meta,null,2));rows.push(`${item.tokenId},"${item.name.replaceAll('"','""')}",${item.dna}`)}await atomic(path.join(out,'csv','collection.csv'),rows.join('\n'));await atomic(path.join(out,'metadata','all.json'),JSON.stringify(payload.metadata.map((x:any)=>x.data),null,2));await atomic(path.join(out,'reports','validation-report.json'),JSON.stringify({valid:true,errors:payload.errors},null,2));await atomic(path.join(out,'reports','generation-manifest.json'),JSON.stringify({engine:'1',seed:payload.project.seed,createdAt:new Date().toISOString(),items:payload.items.length},null,2));await atomic(path.join(out,'project','project-snapshot.json'),JSON.stringify(payload.project,null,2));return out});
