import { useEffect, useMemo, useRef, useState } from 'react';
import { canConnect, connectNodes, edgePath, formatPercent, moveNode, reconnectEdge, validateGraph } from '../core/graph';
import type { Graph, GraphNode, Layer, VisualGroup } from '../core/types';
import { Icon } from './Icon';

type Props = {
  graph: Graph; layers: Layer[]; groups: VisualGroup[]; selectedNode: string | null; selectedEdge: string | null;
onSelectNode(id: string | null): void; onSelectEdge(id: string | null): void;
  onChange(graph: Graph): void; onManage(id: string): void; onQuickAdd(sourceId: string, mode?: 'sequence' | 'branch'): void;
  onDeleteNode(id: string): void; onDeleteEdge(id: string): void;
};
const NODE_W = 154, NODE_H = 72, DRAG_THRESHOLD = 5;

export function GraphCanvas({ graph, layers, groups, selectedNode, selectedEdge, onSelectNode, onSelectEdge, onChange, onManage, onQuickAdd, onDeleteNode, onDeleteEdge }: Props) {
  const [zoom, setZoom] = useState(1); const [pan, setPan] = useState({ x: 0, y: 0 }); const [showMap, setShowMap] = useState(true); const [snap, setSnap] = useState(false); const [menu, setMenu] = useState<{ x: number; y: number; kind: 'node' | 'edge'; id: string } | null>(null); const [choice, setChoice] = useState<{ source: string; x: number; y: number } | null>(null);
  const [connection, setConnection] = useState<{ source: string; edgeId?: string; startX: number; startY: number; x: number; y: number; originX: number; originY: number; dragging: boolean } | null>(null);
  const drag = useRef<{ id: string; clientX: number; clientY: number; nodeX: number; nodeY: number } | null>(null); const viewport = useRef<HTMLDivElement>(null);
  const issues = useMemo(() => validateGraph(graph), [graph]); const nodeById = (id: string) => graph.nodes.find(node => node.id === id);
  const center = () => { setZoom(1); setPan({ x: 0, y: 0 }); };
  useEffect(() => { const key = (event: KeyboardEvent) => { if (event.key === 'Escape') { setConnection(null); setChoice(null); setMenu(null); } if (event.key === 'Delete') { if (selectedNode) onDeleteNode(selectedNode); else if (selectedEdge) onDeleteEdge(selectedEdge); } }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key); }, [selectedNode, selectedEdge, onDeleteNode, onDeleteEdge]);
  const worldPoint = (clientX: number, clientY: number) => { const rect = viewport.current!.getBoundingClientRect(); return { x: (clientX - rect.left - pan.x) / zoom, y: (clientY - rect.top - pan.y) / zoom }; };
  const onPointerMove = (event: React.PointerEvent) => { if (drag.current) { const point = worldPoint(event.clientX, event.clientY); onChange(moveNode(graph, drag.current.id, point.x - drag.current.clientX, point.y - drag.current.clientY, snap)); } if (connection) { const distance = Math.hypot(event.clientX - connection.originX, event.clientY - connection.originY); const point = worldPoint(event.clientX, event.clientY); setConnection({ ...connection, x: point.x, y: point.y, dragging: connection.dragging || distance >= DRAG_THRESHOLD }); } };
  const finishConnection = (event: React.PointerEvent) => { if (drag.current) drag.current = null; if (!connection) return; const target = (document.elementFromPoint(event.clientX, event.clientY) as HTMLElement | null)?.closest<HTMLElement>('[data-input-node]')?.dataset.inputNode; if (connection.dragging) { if (target && canConnect(graph, connection.source, target, connection.edgeId).valid) onChange(connection.edgeId ? reconnectEdge(graph, connection.edgeId, target) : connectNodes(graph, connection.source, target)); } else { const exits = graph.edges.filter(edge => edge.source === connection.source); if (exits.length > 1) setChoice({ source: connection.source, x: event.clientX, y: event.clientY }); else onQuickAdd(connection.source, 'sequence'); } setConnection(null); };
  const startConnector = (event: React.PointerEvent, source: string, edgeId?: string) => { event.stopPropagation(); event.preventDefault(); const node = nodeById(source)!; (event.currentTarget as HTMLElement).setPointerCapture(event.pointerId); setConnection({ source, edgeId, startX: node.x + NODE_W, startY: node.y + NODE_H / 2, x: node.x + NODE_W, y: node.y + NODE_H / 2, originX: event.clientX, originY: event.clientY, dragging: false }); };
  const autoLayout = () => { const depths = new Map<string, number>([['start', 0]]); for (let pass = 0; pass < graph.nodes.length; pass++) for (const edge of graph.edges) if (depths.has(edge.source)) depths.set(edge.target, Math.max(depths.get(edge.target) ?? 0, (depths.get(edge.source) ?? 0) + 1)); const columns = new Map<number, GraphNode[]>(); graph.nodes.forEach(node => { const depth = depths.get(node.id) ?? 1; columns.set(depth, [...(columns.get(depth) ?? []), node]); }); onChange({ ...graph, nodes: graph.nodes.map(node => { const depth = depths.get(node.id) ?? 1, column = columns.get(depth) ?? [], row = column.findIndex(item => item.id === node.id); return { ...node, x: 45 + depth * 215, y: 65 + row * 118 }; }) }); };
  return <div className="graph-shell"><div className="graph-toolbar"><div className="tool-cluster"><button className="icon-button" title="Centra grafo" onClick={center}><Icon name="center"/></button><button className="icon-button" title="Adatta alla schermata" onClick={() => { setZoom(.82); setPan({ x: 0, y: 0 }); }}><Icon name="fit"/></button><button className="tool-button" onClick={autoLayout}><Icon name="wand"/> Organizza automaticamente</button></div><div className="tool-cluster"><label className="snap-toggle"><input type="checkbox" checked={snap} onChange={event => setSnap(event.target.checked)}/> Snap</label><button className={'icon-button ' + (showMap ? 'is-active' : '')} title="Mini-mappa" onClick={() => setShowMap(!showMap)}><Icon name="grid"/></button><button className="zoom" onClick={() => setZoom(1)}>{Math.round(zoom * 100)}%</button></div></div>
    <div ref={viewport} className={'graph-viewport ' + (connection?.dragging ? 'is-connecting' : '')} onPointerMove={onPointerMove} onPointerUp={finishConnection} onWheel={event => { event.preventDefault(); setZoom(value => Math.min(1.4, Math.max(.5, value - event.deltaY * .001))); }} onClick={() => { onSelectNode(null); onSelectEdge(null); setMenu(null); }}>
      <div className="graph-world" style={{ transform: `translate(${pan.x}px,${pan.y}px) scale(${zoom})` }}>{groups.map(group => <div className="visual-group" key={group.id} style={{ left: group.x, top: group.y, width: group.width, height: group.height, borderColor: group.color }}><span style={{ color: group.color }}>{group.name}</span></div>)}
        <svg className="edges" width="1250" height="700" viewBox="0 0 1250 700"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0 8 4 0 8Z"/></marker></defs>{graph.edges.map(edge => { const source = nodeById(edge.source), target = nodeById(edge.target); if (!source || !target) return null; return <g key={edge.id} className={`edge ${selectedEdge === edge.id ? 'active selected' : ''}`} onClick={event => { event.stopPropagation(); onSelectNode(null); onSelectEdge(edge.id); }} onContextMenu={event => { event.preventDefault(); event.stopPropagation(); setMenu({ x: event.clientX, y: event.clientY, kind: 'edge', id: edge.id }); }}><path className="edge-hit" d={edgePath(source, target)}/><path d={edgePath(source, target)}/><foreignObject x={(source.x + NODE_W + target.x) / 2 - 31} y={(source.y + target.y) / 2 + NODE_H / 2 - 14} width="62" height="28"><button className="edge-label" title="Modifica percentuale" onClick={event => { event.stopPropagation(); const value = prompt('Probabilità (%)', String(edge.probability)); if (value !== null && Number.isFinite(Number(value))) onChange({ ...graph, edges: graph.edges.map(item => item.id === edge.id ? { ...item, probability: Number(value) } : item) }); }}>{formatPercent(edge.probability)}</button></foreignObject>{selectedEdge === edge.id && <circle className="edge-handle" cx={target.x} cy={target.y + NODE_H / 2} r="7" onPointerDown={event => startConnector(event, edge.source, edge.id)}/>}</g>; })}{connection?.dragging && <path className="temporary-edge" d={`M${connection.startX} ${connection.startY} C${(connection.startX + connection.x) / 2} ${connection.startY},${(connection.startX + connection.x) / 2} ${connection.y},${connection.x} ${connection.y}`}/>}</svg>
        {graph.nodes.map(node => { const layer = layers.find(item => item.id === node.layerId), error = issues.some(issue => issue.kind === 'error' && issue.nodeId === node.id); const validTarget = connection?.dragging && canConnect(graph, connection.source, node.id, connection.edgeId).valid; return <button key={node.id} className={`graph-node ${node.type} ${selectedNode === node.id ? 'selected' : ''} ${error ? 'invalid' : ''} ${connection?.dragging ? validTarget ? 'valid-target' : 'invalid-target' : ''}`} style={{ left: node.x, top: node.y }} onClick={event => { event.stopPropagation(); onSelectEdge(null); onSelectNode(node.id); }} onDoubleClick={() => node.type === 'layer' && onManage(node.id)} onContextMenu={event => { event.preventDefault(); event.stopPropagation(); if (node.type === 'layer') setMenu({ x: event.clientX, y: event.clientY, kind: 'node', id: node.id }); }} onPointerDown={event => { if ((event.target as HTMLElement).closest('.port,.node-delete')) return; event.stopPropagation(); const point = worldPoint(event.clientX, event.clientY); (event.currentTarget as HTMLElement).setPointerCapture(event.pointerId); drag.current = { id: node.id, clientX: point.x - node.x, clientY: point.y - node.y, nodeX: node.x, nodeY: node.y }; }}><span className="node-icon">{node.type === 'start' ? 'S' : node.type === 'end' ? '✓' : '◇'}</span><span className="node-copy"><strong>{node.type === 'start' ? 'Start' : node.type === 'end' ? 'End' : layer?.name ?? 'Layer mancante'}</strong><small>{node.type === 'start' ? 'Inizio del percorso' : node.type === 'end' ? 'Fine del percorso' : `${layer?.traits.length ?? 0} asset · ${Math.round((layer?.presence ?? 1) * 100)}%`}</small></span>{node.type !== 'end' && <span className="port out" title="Clic: nuovo layer · Trascina: collega" onPointerDown={event => startConnector(event, node.id)}>＋</span>}{node.type !== 'start' && <span className="port in" data-input-node={node.id}/>} {node.type === 'layer' && <span className="node-delete" title="Elimina layer" onClick={event => { event.stopPropagation(); onDeleteNode(node.id); }}>−</span>}{error && <span className="node-alert">!</span>}</button>; })}
      </div>{showMap && <div className="minimap"><div className="mini-world">{graph.nodes.map(node => <i key={node.id} className={node.type} style={{ left: node.x / 7, top: node.y / 7 }}/>)}</div><span>MAPPA</span></div>}{connection?.dragging && <div className="connection-hint">Rilascia su un punto di ingresso · Esc annulla</div>}
    </div>{choice && <div className="branch-popover" style={{ left: Math.min(choice.x, innerWidth - 250), top: Math.min(choice.y, innerHeight - 150) }}><b>Dove aggiungere il layer?</b><button onClick={() => { onQuickAdd(choice.source, 'sequence'); setChoice(null); }}>In sequenza</button><button onClick={() => { onQuickAdd(choice.source, 'branch'); setChoice(null); }}>Nuova diramazione</button></div>}{menu && <div className="context-menu" style={{ left: menu.x, top: menu.y }}><button onClick={() => { if (menu.kind === 'node') onDeleteNode(menu.id); else onDeleteEdge(menu.id); setMenu(null); }}>{menu.kind === 'node' ? 'Elimina layer' : 'Elimina collegamento'}</button></div>}</div>;
}
