import { describe, expect, it } from 'vitest';
import { addLayerAfter, canConnect, connectNodes, deleteLayerNode, edgePath, moveNode, reconnectEdge } from './graph';
import { createNewProjectWorkflow } from './project';
import { migrateProject } from './engine';

describe('editor del grafo unico', () => {
  it('inizializza un nuovo progetto e apre Organizza con Start → End', () => { const workflow = createNewProjectWorkflow(); expect(workflow.phase).toBe('organize'); expect(workflow.selectedNode).toBe('start'); expect(workflow.hint).toContain('Premi +'); expect(workflow.project.graph.nodes.map(node => node.type)).toEqual(['start', 'end']); expect(workflow.project.graph.edges).toEqual([expect.objectContaining({ source: 'start', target: 'end', probability: 100 })]); });
  it('ripara un progetto riaperto senza layer e senza collegamento iniziale', () => { const project = createNewProjectWorkflow().project; const migrated = migrateProject({ ...project, graph: { ...project.graph, edges: [] } }); expect(migrated.graph.edges).toEqual([expect.objectContaining({ source: 'start', target: 'end' })]); });
  it('aggiunge Layer 1 e Layer 2 in sequenza tramite click rapido', () => { const project = createNewProjectWorkflow().project; const first = addLayerAfter(project.graph, project.layers, 'start'); expect(first.layer.name).toBe('Layer 1'); expect(first.graph.edges.map(edge => `${edge.source}>${edge.target}`)).toEqual([`start>${first.nodeId}`, `${first.nodeId}>end`]); const second = addLayerAfter(first.graph, [first.layer], first.nodeId); expect(second.layer.name).toBe('Layer 2'); expect(second.graph.edges.map(edge => `${edge.source}>${edge.target}`)).toEqual([`start>${first.nodeId}`, `${first.nodeId}>${second.nodeId}`, `${second.nodeId}>end`]); });
  it('sposta liberamente Start, End e layer conservando collegamenti e posizioni', () => { const project = createNewProjectWorkflow().project; const added = addLayerAfter(project.graph, [], 'start'); let graph = moveNode(added.graph, 'start', 25, 45); graph = moveNode(graph, 'end', 930, 510); graph = moveNode(graph, added.nodeId, 333, 222); expect(graph.nodes.find(node => node.id === 'start')).toMatchObject({ x: 25, y: 45 }); expect(graph.nodes.find(node => node.id === 'end')).toMatchObject({ x: 930, y: 510 }); const beforePath = edgePath(added.graph.nodes.find(node => node.id === 'start')!, added.graph.nodes.find(node => node.id === added.nodeId)!); const afterPath = edgePath(graph.nodes.find(node => node.id === 'start')!, graph.nodes.find(node => node.id === added.nodeId)!); expect(afterPath).not.toBe(beforePath); expect(graph.edges).toEqual(added.graph.edges); const reopened = migrateProject({ ...project, graph, layers: [added.layer] }); expect(reopened.graph.nodes).toEqual(graph.nodes); });
  it('crea collegamenti manuali e rifiuta duplicati, self-loop e cicli', () => { const project = createNewProjectWorkflow().project; const first = addLayerAfter(project.graph, [], 'start'); const second = addLayerAfter(first.graph, [first.layer], first.nodeId); expect(canConnect(second.graph, 'start', second.nodeId).valid).toBe(true); const branched = connectNodes(second.graph, 'start', second.nodeId); expect(branched.edges.some(edge => edge.source === 'start' && edge.target === second.nodeId)).toBe(true); expect(canConnect(branched, 'start', second.nodeId).valid).toBe(false); expect(canConnect(branched, first.nodeId, first.nodeId).valid).toBe(false); expect(canConnect(branched, 'end', 'start').valid).toBe(false); expect(canConnect(branched, second.nodeId, 'start').valid).toBe(false); });
  it('elimina un layer lineare e riconnette precedente e successivo', () => { const project = createNewProjectWorkflow().project; const first = addLayerAfter(project.graph, [], 'start'); const second = addLayerAfter(first.graph, [first.layer], first.nodeId); const deleted = deleteLayerNode(second.graph, first.nodeId, true); expect(deleted.nodes.some(node => node.id === first.nodeId)).toBe(false); expect(deleted.edges.some(edge => edge.source === 'start' && edge.target === second.nodeId)).toBe(true); });
  it('riconnette una linea senza creare cicli', () => { const project = createNewProjectWorkflow().project; const first = addLayerAfter(project.graph, [], 'start'); const second = addLayerAfter(first.graph, [first.layer], first.nodeId); const edge = second.graph.edges.find(item => item.source === first.nodeId)!; const unchanged = reconnectEdge(second.graph, edge.id, 'start'); expect(unchanged).toEqual(second.graph); });
});
